package com.onewelcome.showcaseapp

import android.os.Build
import com.onegini.mobile.sdk.android.model.OneginiClientConfigModel

class OneginiConfigModel : OneginiClientConfigModel {
  /* Config model generated by SDK Configurator version: v6.0.0 */
  override val appIdentifier = "ExampleApp"
  override val appPlatform = "android"
  override val redirectUri = "oneginiexample://loginsuccess"
  override val appVersion = "7.10.0"
  override val baseUrl = "https://mobile-security-proxy.onegini.com"
  override val resourceBaseUrl = "https://mobile-security-proxy.onegini.com/resources/"
  override val keyStoreHash = "0772c1f63f872e1f66f2431ccd9a07bb795f3d35234475630dd8b9eae800f9a1"
  override val serverPublicKey: String? = null
  override val serverType = "access"
  override val serverVersion = "1.61.0"
  override val certificatePinningKeyStore = R.raw.keystore
  override val deviceName = "${Build.BRAND} ${Build.MODEL}"

  override fun toString(): String {
    return "ConfigModel{" +
        "  appIdentifier='" + appIdentifier + "'" +
        ", appPlatform='" + appPlatform + "'" +
        ", redirectUri='" + redirectUri + "'" +
        ", appVersion='" + appVersion + "'" +
        ", baseUrl='" + baseUrl + "'" +
        ", resourceBaseUrl='" + resourceBaseUrl + "'" +
        ", keyStoreHash='" + keyStoreHash + "'" +
        ", serverPublicKey='" + serverPublicKey + "'" +
        ", serverType='" + serverType + "'" +
        ", serverVersion='" + serverVersion + "'" +
        "}"
  }
}
